apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dd-tracing
    tags.datadoghq.com/env: "dev"
    tags.datadoghq.com/service: "nodejs"
    tags.datadoghq.com/version: "v1.1"

  name: dd-tracing
spec:
  selector:
    matchLabels:
      app: dd-tracing
  replicas: 2
  template:
    metadata:
      labels:
        app: dd-tracing
        tags.datadoghq.com/env: "dev"
        tags.datadoghq.com/service: "nodejs"
        tags.datadoghq.com/version: "v1.1"

    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: DD_ENV
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/env']
        - name: DD_SERVICE
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/service']
        - name: DD_VERSION
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['tags.datadoghq.com/version']

        name: dd-tracing
        image: jilsx/dd-trace:nodejs
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
