apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: dd-tracing
  name: dd-tracing
spec:
  selector:
    matchLabels:
      app: dd-tracing
  replicas: 2
  template:
    metadata:
      labels:
        app: dd-tracing
    spec:
      containers:
      - env:
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        name: dd-tracing
        image: jilsx/dd-trace
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 512Mi
